# 推送通知
host-suffix, push.apple.com, direct
host-suffix, akadns.net, direct
host-keyword, apple.com.edgekey.net, direct
ip-cidr, 17.0.0.0/8, direct, no-resolve
ip-cidr, 17.249.0.0/16, direct, no-resolve
ip-cidr, 17.252.0.0/16, direct, no-resolve
ip-cidr, 17.57.144.0/22, direct, no-resolve
ip-cidr, 17.188.128.0/18, direct, no-resolve
ip-cidr, 17.188.20.0/23, direct, no-resolve
ip6-cidr, 2620:149:a44::/48, direct, no-resolve
ip6-cidr, 2403:300:a42::/48, direct, no-resolve
ip6-cidr, 2403:300:a51::/48, direct, no-resolve
ip6-cidr, 2a01:b740:a42::/48, direct, no-resolve

# APNs 证书请求门户
host, identity.apple.com, direct
host-suffix, push.apple.com, direct
