#!desc=哔哩哔哩广告净化[墨鱼直用版]
name: bilibili_ads_clean
desc: 完美过滤 B 站开屏、视频/直播间广告、动态推荐及搜索框填词（直接引用官方 JS，免配置直接使用）
author: "@ddgksf2013"

http:
  mitm:
    - "app.bilibili.com"
    - "api.live.bilibili.com"
    - "*.bilibili.com"
    - "*.bili*.*"
    - "*.bilibili.*"
    - "grpc.biliapi.net"
    - "*biliapi.net"

  script:
    # --- BiliJson 脚本处理 ---
    - name: bili_json
      match: ^https?:\/\/(api\.bili(api|bili)\.(net|com)\/pgc\/season\/app\/related\/recommend\?|api\.live\.bilibili\.com\/xlive\/(e-commerce-interface\/v\d\/ecommerce-user\/get_shopping_info\?|app-room\/v1\/index\/getInfoByRoom)|app\.bilibili\.com\/x\/v2\/splash\/list|app\.bilibili\.com\/x\/v2\/account\/myinfo\?|api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed|app\.bilibili\.com\/x\/v2\/feed\/index|api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/(bangumi|cinema\/tab\?)|app\.bilibili\.com\/x\/resource\/show\/tab|app\.bilibili\.com\/x\/v2\/account\/mine|app\.bilibili\.com\/x\/resource\/top\/activity|app\.bilibili\.com\/x\/v2\/search\/square)
      type: response
      require-body: true
      timeout: 10

    # --- BiliProto 脚本处理 ---
    - name: bili_proto
      match: ^https?:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/(bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$|bilibili\.community\.service\.dm\.v1\.DM\/(DmView|DmSegMobile)|bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus|bilibili\.app\.(view|viewunite)\.v1\.View\/(View|TFInfo)$|bilibili\.app\.dynamic\.v2\.Dynamic\/Dyn(All|Video)$)
      type: response
      require-body: true
      binary-mode: true
      timeout: 10

  rewrite:
    # 纯拒绝类的广告/追踪接口（直接使用 Stash 本地拦截）
    - ^https?:\/\/bilibili\.2025\.04\.02\/c136 - reject-200
    - ^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - reject-200
    - ^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - reject-200
    - ^https:\/\/api\.bilibili\.com\/pgc\/season\/player\/cards - reject-200
    - ^https?:\/\/api\.bilibili\.com\/pgc\/season\/player\/ogv\/cards - reject-200
    - ^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/show - reject-200
    - ^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash|GetActivityTab) - reject-200
    - ^https?:\/\/app\.bilibili\.com\/x\/v\d\/search\/defaultwords - reject-200
    - ^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/Default - reject-200

# Stash 后台托管的官方远程 JS 地址（直接拉取原作者最新代码）
script-providers:
  bili_json:
    url: https://ddgksf2013.top/scripts/bilibili.ads.js
    interval: 86400

  bili_proto:
    url: https://github.com/BiliUniverse/ADBlock/releases/download/v0.6.19/response.bundle.js
    interval: 86400
